name: Create Labels With Japanese

on:
    push:
        branches:
            - depelop

jobs:
    create-labels:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Create labels With Japanese
              uses: actions/github-script@v6
              with:
                  script: |
                      const { Octokit } = require('@octokit/rest');
                      const octokit = new Octokit({ auth: ${{ secrets.GITHUB_TOKEN }} });

                      const labels = [
                        { name: 'ドキュメント', color: '#2196f3', description: 'ドキュメントに関する内容' },
                        { name: 'バグ', color: '#f44336', description: 'バグに関する内容' },
                        { name: 'リクエスト', color: '#03a9f4', description: '要望に関する内容' },
                        { name: '不採用', color: '#FFFFFF', description: 'Issuesの内容を不採用にする場合' },
                        { name: '新機能', color: '#4caf50', description: '新機能に関する内容' },
                        { name: '注意', color: '#ffeb3b', description: '注意に関する内容' },
                        { name: '無効', color: '#8bc34a', description: 'Issuesが無効な内容' },
                        { name: '質問', color: '#9c27b0', description: '質問の関する内容' },
                        { name: '重複', color: '#9e9e9e', description: 'Issuesの内容が重複している場合' },
                      ];

                      for (const label of labels) {
                        octokit.issues.createLabel({
                          owner: context.repo.owner,
                          repo: context.repo.repo,
                          name: label.name,
                          color: label.color
                          description: label.description
                        });
                      }
